apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: therivers.cardgames.aaroneaton.com
spec:
  claimNames:
    kind: DealTheRiver
    plural: dealtherivers
  group: cardgames.aaroneaton.com
  names:
    kind: TheRiver
    plural: therivers
  connectionSecretKeys:
    - "01"
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tableName:
                  type: string
                  description: Name of Table for this River
              required:
                - tableName
