apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  # Install Univerasal Crossplane (uxp).
  - command: helm install universal-crossplane https://charts.upbound.io/stable/universal-crossplane-1.5.1-up.1.tgz --namespace upbound-system --wait --create-namespace --values tests/uxp-values.yaml
  # Wait for provider-aws to become healthy.
  - command: kubectl wait --for condition=healthy  --timeout=300s provider/crossplane-provider-aws
  # Install ProviderConfig for test.
  - command: kubectl apply -f tests/init/
testDirs:
  - tests/compositions/
startKIND: true
kindContext: kuttl-test
skipClusterDelete: false
